server:
  port: 8091
# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

## 数据库配置；启动时配置数据库资源信息
spring:
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding.yml
  config:
    import:
      - "nacos:market-app-dev.yml?group=DEFAULT_GROUP"
  nacos:
    config:
      server-addr: 127.0.0.1:8848
# MyBatis 配置【如需使用记得打开】
#mybatis:
#  mapper-locations: classpath:/mybatis/mapper/*.xml
#  config-location:  classpath:/mybatis/config/mybatis-config.xml
# Redis
redis:
  sdk:
    config:
      host: 127.0.0.1
      port: 16379
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: market_producer_group
  topic:
    activity_sku_stock_zero: "activity_sku_stock_zero"
    send_award: "send_award"
    send_rebate: "send_rebate"
    credit_adjust_success: "credit_adjust_success"
# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml
dubbo:
  application:
    name: market
    version: 1.0
  registry:
    id: nacos-registry
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: com.liubo.api

app:
  config:
    api-version: v1