server:
  port: 8091

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

## 数据库配置；启动时配置数据库资源信息
spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding.yml

# MyBatis 配置【如需使用记得打开】
#mybatis:
#  mapper-locations: classpath:/mybatis/mapper/*.xml
#  config-location:  classpath:/mybatis/config/mybatis-config.xml
# Redis
redis:
  sdk:
    config:
      host: 127.0.0.1
      port: 16379
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: market_producer_group
  topic:
    activity_sku_stock_zero: "activity_sku_stock_zero"
# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml

app:
  config:
    api-version: v1